# -*- coding: utf-8 -*-
"""module7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zW5hYefyCgAEdiGOWy9GBKfm7Jit7nX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

df = pd.read_csv('/content/customer_segmentation.csv')

df = df.copy()
df['Age'] = 2025 - df['Year_Birth']
df['TotalChildren'] = df['Kidhome'] + df['Teenhome']
df['TotalSpent'] = df[['MntWines', 'MntFruits', 'MntMeatProducts',
                       'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']].sum(axis=1)

df_cluster = df[['Income', 'Age', 'TotalChildren', 'Recency', 'TotalSpent']].dropna()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster)

inertia = []
sil_scores = []
K = range(2, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)
    sil_scores.append(silhouette_score(X_scaled, kmeans.labels_))

# Plot elbow + silhouette
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(K, inertia, 'bo-')
plt.title('K-Means Elbow Curve')
plt.xlabel('k'), plt.ylabel('Inertia')

plt.subplot(1, 2, 2)
plt.plot(K, sil_scores, 'go-')
plt.title('Silhouette Score')
plt.xlabel('k'), plt.ylabel('Score')
plt.tight_layout()
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
df_cluster['KMeans_Cluster'] = kmeans.fit_predict(X_scaled)

df_cluster.groupby('KMeans_Cluster').mean()

linked = linkage(X_scaled, method='ward')
plt.figure(figsize=(10, 5))
dendrogram(linked, truncate_mode='lastp', p=10)
plt.title("Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Distance")
plt.show()

df_cluster['Hierarchical_Cluster'] = fcluster(linked, t=4, criterion='maxclust')

print(df_cluster[['KMeans_Cluster', 'Hierarchical_Cluster']].value_counts())

pd.crosstab(df_cluster['KMeans_Cluster'], df_cluster['Hierarchical_Cluster'])

