# -*- coding: utf-8 -*-
"""p_assesment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ir-T9Hzsc-07_lnoOts9upgWofk7nZ9O
"""

print("welcome to fruit market:")
print("1.Manager")
print("2.Customer")
a=int(input("enter your choice:"))
print("select your Role:",a)
if a==1:
    print("1.Add Fruit stock")
    print("2.View Fruit stock")
    print("3.Update Fruit stock")
b=int(input("enter your choice:",))
print(b)
if b==1:
  print("Add Fruit stock")
  c=input("Enter Fruit Name:")
  d=int(input("Enter qty (in kg):"))
  e=int(input("Enter Price:"))

if a==1:
    print("welcome Manager")